import { Specialist, Project, Property } from "../types";

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "3",
    title: "Sector 70 Builder Floor",
    description: "Well-maintained 2 BHK semi-furnished builder floor in a peaceful residential pocket of Sector 70. Features modular kitchen, dedicated covered parking, uninterrupted power backup, and easy access to NH-44.",
    price: 15000,
    location: "Sector 70, Mohali, Punjab",
    type: "apartment",
    status: "available",
    listingType: "rent",
    ownershipType: "dealer",
    tenantTypes: ["Independent", "Family", "Working Professionals"],
    distanceKm: 8,
    rent: 15000,
    deposit: 30000,
    brokerage: 15000,
    maintenance: 1500,
    beds: 2,
    baths: 2,
    sqft: 1050,
    carpetArea: 850,
    balconies: 1,
    parking: "1 Open Parking",
    facing: "East",
    floorDetails: "Ground Floor of 3",
    furnishingStatus: "Semi-Furnished",
    possessionStatus: "Ready to Move",
    waterSupply: "Corporation Water + Borewell",
    electricityBackup: "Full Backup (Inverter)",
    internet: "Airtel Fiber Available",
    address: "H.No. 456, Sector 70, SAS Nagar, Mohali – 160071, Punjab",
    images: [
        "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1200&q=80",
        "https://images.unsplash.com/photo-1600121848594-d86cc4f59500?w=1200&q=80"
    ],
    videoUrl: "https://cdn.pixabay.com/video/2016/09/13/5108-182390623_tiny.mp4",
    previewVideoUrl: "https://cdn.pixabay.com/video/2016/09/13/5108-182390623_tiny.mp4",
    features: ["Power Backup", "Covered Parking", "24/7 Security"],
    yearBuilt: 2019,
    agentId: "spec-1",
    verified: true,
    rating: 4.3,
    totalViews: 580
  },
  {
    id: "6",
    title: "Purab Premium Apartments",
    description: "Spacious 2 BHK apartment in GMADA's landmark 37-acre gated township in Sector 88. Enjoy 2 swimming pools, a fully operational community centre, basketball court, lawn tennis, and piped gas.",
    price: 10000,
    location: "Sector 88, Mohali, Punjab",
    type: "apartment",
    status: "available",
    listingType: "rent",
    ownershipType: "owner",
    tenantTypes: ["Family", "Couple", "Working Professionals"],
    distanceKm: 12,
    rent: 10000,
    deposit: 20000,
    brokerage: 0,
    maintenance: 2000,
    beds: 2,
    baths: 2,
    sqft: 1650,
    carpetArea: 1250,
    balconies: 2,
    parking: "1 Covered Parking",
    facing: "North-East",
    floorDetails: "4th Floor of 12",
    furnishingStatus: "Semi-Furnished",
    possessionStatus: "Ready to Move",
    waterSupply: "24/7 Municipality Water",
    electricityBackup: "DG Generator Backup",
    internet: "Jio Fiber, Airtel Available",
    address: "Purab Premium Apartments, Sector 88, SAS Nagar, Mohali – 160070, Punjab",
    images: [
        "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80"
    ],
    videoUrl: "https://cdn.pixabay.com/video/2022/05/24/118029-712882740_tiny.mp4",
    previewVideoUrl: "https://cdn.pixabay.com/video/2022/05/24/118029-712882740_tiny.mp4",
    features: ["2 Swimming Pools", "Clubhouse", "Piped Gas"],
    yearBuilt: 2018,
    agentId: "spec-2",
    verified: true,
    rating: 4.6,
    totalViews: 1500
  },
  {
    id: "8",
    title: "Phase 3B2 Residential Floor",
    description: "Affordable 2 BHK ground-floor unit with tiled flooring, modular kitchen, attached bathroom, and open parking. Quiet locality with good connectivity to Chandigarh via Airport Road.",
    price: 10000,
    location: "Phase 3B2, Mohali, Punjab",
    type: "apartment",
    status: "available",
    listingType: "rent",
    ownershipType: "owner",
    tenantTypes: ["Independent", "Boys", "Working Professionals"],
    distanceKm: 5,
    rent: 10000,
    deposit: 20000,
    brokerage: 0,
    maintenance: 1000,
    beds: 2,
    baths: 1,
    sqft: 1000,
    carpetArea: 800,
    balconies: 1,
    parking: "1 Open Parking",
    facing: "West",
    floorDetails: "Ground Floor of 2",
    furnishingStatus: "Semi-Furnished",
    possessionStatus: "Ready to Move",
    waterSupply: "Borewell + Tanker Backup",
    electricityBackup: "Inverter Backup",
    internet: "Airtel Broadband Available",
    address: "Plot No. 234, Phase 3B2, SAS Nagar, Mohali – 160059, Punjab",
    images: [
        "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80"
    ],
    videoUrl: "https://cdn.pixabay.com/video/2022/04/18/114382-699318851_tiny.mp4",
    previewVideoUrl: "https://cdn.pixabay.com/video/2022/04/18/114382-699318851_tiny.mp4",
    features: ["Modular Kitchen", "Open Parking", "CCTV"],
    yearBuilt: 2017,
    agentId: "spec-2",
    verified: true,
    rating: 4.1,
    totalViews: 890
  },
  {
    id: "9",
    title: "Aerocity Studio Suite",
    description: "Compact fully furnished studio near Aerocity with smart storage, balcony, high-speed internet, and easy access to IT offices. Ideal for working professionals and couples.",
    price: 18500,
    location: "Aerocity Block C, Mohali, Punjab",
    type: "studio",
    status: "available",
    listingType: "rent",
    ownershipType: "dealer",
    tenantTypes: ["Couple", "Working Professionals", "Independent"],
    distanceKm: 3,
    rent: 18500,
    deposit: 37000,
    brokerage: 18500,
    maintenance: 1200,
    beds: 1,
    baths: 1,
    sqft: 620,
    carpetArea: 510,
    balconies: 1,
    parking: "Basement Parking",
    facing: "South",
    floorDetails: "6th Floor of 11",
    furnishingStatus: "Fully-Furnished",
    possessionStatus: "Ready to Move",
    waterSupply: "24/7 Municipal Water",
    electricityBackup: "Power Backup",
    internet: "Airtel Fiber Installed",
    address: "Block C, Aerocity, SAS Nagar, Mohali - 140306, Punjab",
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80"
    ],
    previewVideoUrl: "https://cdn.pixabay.com/video/2019/10/09/27669-365224683_tiny.mp4",
    features: ["Fully Furnished", "Fiber Internet", "Balcony"],
    yearBuilt: 2021,
    agentId: "spec-1",
    verified: true,
    rating: 4.4,
    totalViews: 760
  },
  {
    id: "10",
    title: "Girls PG Near Chandigarh University",
    description: "Secure girls PG with meals, laundry, study lounge, biometric entry, and shuttle connectivity. Designed for students looking for a clean and managed stay.",
    price: 12000,
    location: "Gharuan, Kharar, Punjab",
    type: "pg",
    status: "available",
    listingType: "rent",
    ownershipType: "owner",
    tenantTypes: ["Girls", "Independent"],
    distanceKm: 15,
    rent: 12000,
    deposit: 12000,
    brokerage: 0,
    maintenance: 0,
    beds: 1,
    baths: 1,
    sqft: 320,
    carpetArea: 260,
    balconies: 0,
    parking: "Two-Wheeler Parking",
    facing: "East",
    floorDetails: "2nd Floor of 4",
    furnishingStatus: "Fully-Furnished",
    possessionStatus: "Ready to Move",
    waterSupply: "24/7 Water",
    electricityBackup: "Inverter Backup",
    internet: "Wi-Fi Included",
    address: "Gharuan Main Road, Near Chandigarh University, Kharar - 140413, Punjab",
    images: [
      "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200&q=80"
    ],
    features: ["Meals Included", "Laundry", "Biometric Entry"],
    yearBuilt: 2020,
    agentId: "spec-2",
    verified: true,
    rating: 4.2,
    totalViews: 1320
  },
  {
    id: "11",
    title: "Family Apartment in Sector 82",
    description: "Freshly painted 3 BHK family apartment in a gated society with lift, park-facing balcony, modular kitchen, and quick access to Airport Road.",
    price: 24500,
    location: "Sector 82, Mohali, Punjab",
    type: "apartment",
    status: "available",
    listingType: "rent",
    ownershipType: "dealer",
    tenantTypes: ["Family", "Working Professionals"],
    distanceKm: 18,
    rent: 24500,
    deposit: 49000,
    brokerage: 24500,
    maintenance: 2500,
    beds: 3,
    baths: 2,
    sqft: 1720,
    carpetArea: 1320,
    balconies: 2,
    parking: "1 Covered Parking",
    facing: "North",
    floorDetails: "8th Floor of 14",
    furnishingStatus: "Semi-Furnished",
    possessionStatus: "Ready to Move",
    waterSupply: "24/7 Society Water",
    electricityBackup: "DG Backup",
    internet: "Jio Fiber Available",
    address: "Sector 82 Gated Society, SAS Nagar, Mohali - 160062, Punjab",
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80",
      "https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=1200&q=80"
    ],
    previewVideoUrl: "https://cdn.pixabay.com/video/2020/04/18/36413-411782086_tiny.mp4",
    features: ["Gated Society", "Park Facing", "Lift"],
    yearBuilt: 2022,
    agentId: "spec-1",
    verified: true,
    rating: 4.7,
    totalViews: 1740
  },
  {
    id: "12",
    title: "Boys Co-Living in Phase 7",
    description: "Managed boys co-living with housekeeping, shared lounge, pantry, CCTV, and flexible lock-in. Close to cafes, coaching centers, and public transport.",
    price: 8500,
    location: "Phase 7, Mohali, Punjab",
    type: "co-living",
    status: "available",
    listingType: "rent",
    ownershipType: "dealer",
    tenantTypes: ["Boys", "Working Professionals", "Independent"],
    distanceKm: 9,
    rent: 8500,
    deposit: 8500,
    brokerage: 0,
    maintenance: 500,
    beds: 1,
    baths: 1,
    sqft: 280,
    carpetArea: 220,
    balconies: 0,
    parking: "Street Parking",
    facing: "West",
    floorDetails: "1st Floor of 3",
    furnishingStatus: "Fully-Furnished",
    possessionStatus: "Ready to Move",
    waterSupply: "24/7 Water",
    electricityBackup: "Inverter Backup",
    internet: "Wi-Fi Included",
    address: "Phase 7 Market Road, SAS Nagar, Mohali - 160062, Punjab",
    images: [
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200&q=80"
    ],
    features: ["Housekeeping", "CCTV", "Shared Lounge"],
    yearBuilt: 2019,
    agentId: "spec-2",
    verified: true,
    rating: 4.0,
    totalViews: 980
  },
  {
    id: "13",
    title: "Independent Kothi Floor",
    description: "Premium independent first floor with separate entry, front sit-out, modular kitchen, and dedicated car parking. Suitable for families seeking privacy.",
    price: 30000,
    location: "Sector 69, Mohali, Punjab",
    type: "independent",
    status: "available",
    listingType: "rent",
    ownershipType: "owner",
    tenantTypes: ["Independent", "Family"],
    distanceKm: 20,
    rent: 30000,
    deposit: 60000,
    brokerage: 0,
    maintenance: 1500,
    beds: 3,
    baths: 3,
    sqft: 1900,
    carpetArea: 1500,
    balconies: 2,
    parking: "2 Car Parking",
    facing: "East",
    floorDetails: "1st Floor of 2",
    furnishingStatus: "Semi-Furnished",
    possessionStatus: "Ready to Move",
    waterSupply: "Municipal + Borewell",
    electricityBackup: "Inverter Backup",
    internet: "Fiber Ready",
    address: "Sector 69, SAS Nagar, Mohali - 160062, Punjab",
    images: [
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=1200&q=80",
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1200&q=80"
    ],
    previewVideoUrl: "https://cdn.pixabay.com/video/2023/06/05/166165-833775026_tiny.mp4",
    features: ["Separate Entry", "Owner Listed", "Private Parking"],
    yearBuilt: 2018,
    agentId: "spec-1",
    verified: true,
    rating: 4.8,
    totalViews: 1210
  },
  {
    id: "1",
    title: "Amayra Sky City",
    description: "RERA-approved premium 3 BHK apartments in a Vastu-friendly gated township on Kharar–Daun Majra Highway. Features a modern clubhouse, fully equipped gym, landscaped gardens, swimming pool, and children's play areas. RERA No: PBRERA-SAS80-PR1219.",
    price: 4200000,
    location: "Kharar–Daun Majra Highway, Kharar, SAS Nagar Mohali",
    type: "apartment",
    status: "available",
    listingType: "buy",
    maintenance: 3500,
    beds: 3,
    baths: 2,
    sqft: 1338,
    carpetArea: 980,
    balconies: 2,
    parking: "2 Covered Parking",
    facing: "South-East",
    floorDetails: "7th Floor of 15",
    furnishingStatus: "Unfurnished",
    possessionStatus: "Under Construction (Dec 2026)",
    waterSupply: "24/7 Corporation Water + RO Plant",
    electricityBackup: "Full Power Backup",
    internet: "Fiber Optic Ready",
    address: "Amayra Sky City, Kharar–Daun Majra Highway, Kharar, SAS Nagar – 140301, Punjab",
    images: [
        "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=80",
        "https://images.unsplash.com/photo-1600585154526-990dcea4db0d?w=1200&q=80"
    ],
    videoUrl: "https://cdn.pixabay.com/video/2021/04/12/70860-538164098_tiny.mp4",
    previewVideoUrl: "https://cdn.pixabay.com/video/2021/04/12/70860-538164098_tiny.mp4",
    features: ["RERA Approved", "Swimming Pool", "Children's Play Area"],
    yearBuilt: 2025,
    agentId: "spec-1",
    verified: true,
    rating: 4.7,
    totalViews: 2100
  },
  {
    id: "2",
    title: "Nirwana The Moksha",
    description: "Premium 3 BHK apartments set amidst lush green surroundings in Kharar. Spacious rooms, modular kitchen, laminated flooring, and excellent road connectivity to Chandigarh. Ideal for families seeking calm and comfort.",
    price: 4503000,
    location: "Sector 125, Kharar, SAS Nagar Mohali",
    type: "apartment",
    status: "reserved",
    listingType: "buy",
    maintenance: 3000,
    beds: 3,
    baths: 3,
    sqft: 1550,
    carpetArea: 1150,
    balconies: 2,
    parking: "1 Covered Parking",
    facing: "North",
    floorDetails: "3rd Floor of 10",
    furnishingStatus: "Unfurnished",
    possessionStatus: "Ready to Move",
    waterSupply: "24/7 Municipality Water",
    electricityBackup: "Full Power Backup",
    internet: "Jio Fiber, Airtel Available",
    address: "Nirwana The Moksha, Sector 125, Kharar, SAS Nagar – 140301, Punjab",
    images: [
        "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80",
        "https://images.unsplash.com/photo-1600585154526-990dcea4db0d?w=1200&q=80"
    ],
    videoUrl: "https://cdn.pixabay.com/video/2024/02/22/201467-915447194_tiny.mp4",
    previewVideoUrl: "https://cdn.pixabay.com/video/2024/02/22/201467-915447194_tiny.mp4",
    features: ["Landscaped Gardens", "Gym", "Power Backup"],
    yearBuilt: 2024,
    agentId: "spec-2",
    verified: true,
    rating: 4.5,
    totalViews: 850
  },
  {
    id: "4",
    title: "Golden Avenue",
    description: "Ready-to-move 3 BHK apartments on Landran–Kharar Road with premium Italian marble flooring, large balconies, and unobstructed views. Gated complex with 24/7 security, covered parking, and rainwater harvesting.",
    price: 7290000,
    location: "Sector 115, Landran–Kharar Road, Mohali",
    type: "apartment",
    status: "available",
    listingType: "buy",
    maintenance: 4000,
    beds: 3,
    baths: 3,
    sqft: 1850,
    carpetArea: 1380,
    balconies: 3,
    parking: "2 Covered Parking",
    facing: "East",
    floorDetails: "5th Floor of 8",
    furnishingStatus: "Unfurnished",
    possessionStatus: "Ready to Move",
    waterSupply: "24/7 Corporation + Borewell",
    electricityBackup: "Full Power Backup + DG",
    internet: "Jio Fiber Available",
    address: "Golden Avenue, Sector 115, Landran–Kharar Road, Mohali – 140301, Punjab",
    images: [
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80"
    ],
    videoUrl: "https://cdn.pixabay.com/video/2023/11/02/187497-880295191_tiny.mp4",
    previewVideoUrl: "https://cdn.pixabay.com/video/2023/11/02/187497-880295191_tiny.mp4",
    features: ["Ready to Move", "Covered Parking", "Rainwater Harvesting"],
    yearBuilt: 2023,
    agentId: "spec-2",
    verified: true,
    rating: 4.8,
    totalViews: 3200
  },
  {
    id: "5",
    title: "Ubber Mews Gate",
    description: "High-rise 3 BHK apartments with panoramic views of the Shivalik Hills on Kharar Mohali Road. Premium finishes, a rich-lifestyle clubhouse, EV charging bays, and a rooftop lounge make this a standout address.",
    price: 7799000,
    location: "Kharar Mohali Road, Kharar, SAS Nagar",
    type: "apartment",
    status: "available",
    listingType: "buy",
    maintenance: 4500,
    beds: 3,
    baths: 3,
    sqft: 1950,
    carpetArea: 1450,
    balconies: 2,
    parking: "2 Covered + 1 Open Parking",
    facing: "South-West",
    floorDetails: "10th Floor of 18",
    furnishingStatus: "Unfurnished",
    possessionStatus: "Ready to Move",
    waterSupply: "24/7 Corporation Water",
    electricityBackup: "Full Power Backup",
    internet: "Fiber Optic Ready",
    address: "Ubber Mews Gate, Kharar Mohali Road, Kharar, SAS Nagar – 140301, Punjab",
    images: [
        "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80"
    ],
    videoUrl: "https://cdn.pixabay.com/video/2023/10/19/185652-876119131_tiny.mp4",
    previewVideoUrl: "https://cdn.pixabay.com/video/2023/10/19/185652-876119131_tiny.mp4",
    features: ["Hill Views", "EV Charging", "Rooftop Lounge"],
    yearBuilt: 2024,
    agentId: "spec-1",
    verified: false,
    rating: 4.6,
    totalViews: 980
  },
  {
    id: "7",
    title: "Nirwana Heights",
    description: "Ultra-luxury 4 BHK apartments with private terraces on the Chandigarh–Kurali Highway. Featuring concierge service, a rooftop infinity pool, fully loaded gym, and smart home automation. A landmark address near the Chandigarh International Airport.",
    price: 10500000,
    location: "Chandigarh–Kurali Highway, Kharar, SAS Nagar",
    type: "apartment",
    status: "available",
    listingType: "buy",
    maintenance: 7500,
    beds: 4,
    baths: 4,
    sqft: 2400,
    carpetArea: 1800,
    balconies: 3,
    parking: "2 Covered + 1 EV Bay",
    facing: "North-East (Shivalik View)",
    floorDetails: "12th Floor of 20",
    furnishingStatus: "Unfurnished",
    possessionStatus: "Ready to Move",
    waterSupply: "24/7 RO + Softener System",
    electricityBackup: "Full Backup + Solar Panels",
    internet: "Dedicated Fiber + Smart Home Network",
    address: "Nirwana Heights, Chandigarh–Kurali Highway, Kharar, SAS Nagar – 140301, Punjab",
    images: [
        "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80"
    ],
    videoUrl: "https://cdn.pixabay.com/video/2020/07/28/45793-445831671_tiny.mp4",
    previewVideoUrl: "https://cdn.pixabay.com/video/2020/07/28/45793-445831671_tiny.mp4",
    features: ["Private Terrace", "Infinity Pool", "Smart Home"],
    yearBuilt: 2025,
    agentId: "spec-1",
    verified: true,
    rating: 4.9,
    totalViews: 1100
  }
];

export const MOCK_SPECIALISTS: Specialist[] = [
  {
    id: "spec-1",
    name: "Alex Vanhout",
    company: "Neo-Prime Reality",
    role: "Luxury Investment Advisor",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80",
    coverImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80",
    verified: true,
    specialization: ["Luxury Homes", "Investment Advisor"],
    experience: 12,
    totalProperties: 14,
    dealsClosed: 215,
    rating: 4.9,
    reviewCount: 84,
    responseTime: "< 2 hours",
    availability: "online",
    languages: ["English", "Japanese", "German"],
    location: "Sector 7, Neo-Tokyo",
    bio: "Specializing in ultra-luxe penthouses and quantum-secure residential nodes. I help global citizens find their anchor in the digital age.",
    phone: "+81 90-XXXX-XXXX",
    email: "alex@neoprime.is",
    whatsapp: "+81 90-XXXX-XXXX"
  },
  {
    id: "spec-2",
    name: "Satoshi Nakamoto",
    company: "Core District Group",
    role: "Commercial Specialist",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80",
    coverImage: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&q=80",
    verified: true,
    specialization: ["Commercial Properties", "New Projects"],
    experience: 15,
    totalProperties: 32,
    dealsClosed: 480,
    rating: 4.8,
    reviewCount: 156,
    responseTime: "< 30 mins",
    availability: "busy",
    languages: ["English", "Mandarin"],
    location: "Central Core, Sector 2",
    bio: "Focusing on high-yield industrial nodes and modular office clusters. Efficiency is the only currency that matters.",
    phone: "+81 3-XXXX-XXXX",
    email: "satoshi@coredistrict.io",
    whatsapp: "+81 3-XXXX-XXXX"
  }
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-1",
    name: "Aegis Zenith Clusters",
    builderName: "Quantum Foundations",
    builderLogo: "https://api.dicebear.com/7.x/identicon/svg?seed=Quantum",
    type: "residential",
    status: "newly-launched",
    possessionDate: "Q4 2026",
    priceStarting: 4500000,
    location: "Sector 9, Sky Harbor",
    size: "24 Acres",
    towers: 8,
    units: 1200,
    reraApproved: true,
    luxury: true,
    completionPercentage: 15,
    coverImage: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80"
    ],
    description: "The peak of integrated living. Aegis Zenith offers self-sustaining energy nodes and advanced liquid-cooled architectures for the ultimate comfort.",
    amenities: ["Quantum Pool", "AI Gym", "Shared Workspace", "EV Dock", "24/7 Security", "Zen Garden"],
    nearbyLandmarks: [
        { name: "Hyperloop Station S9", distance: "0.5 KM" },
        { name: "Sector 9 Medical Center", distance: "1.2 KM" }
    ],
    floorPlans: [
      { type: "2 BHK Elite", area: "1450 sqft", price: 4500000, image: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800" },
      { type: "3 BHK Royal", area: "2100 sqft", price: 6200000, image: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800" }
    ]
  },
  {
    id: "proj-2",
    name: "Vector Commercial Hub",
    builderName: "Steel & Logic",
    builderLogo: "https://api.dicebear.com/7.x/identicon/svg?seed=Steel",
    type: "commercial",
    status: "under-construction",
    possessionDate: "Q2 2025",
    priceStarting: 12000000,
    location: "Central Core, Sector 1",
    size: "5 Acres",
    towers: 2,
    units: 450,
    reraApproved: true,
    luxury: false,
    completionPercentage: 65,
    coverImage: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&q=80",
    gallery: [
        "https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&q=80",
        "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80"
    ],
    description: "The engine of Neo-Tokyo. Premium office spaces with direct fiber link and sub-millisecond trading latency.",
    amenities: ["Direct Fiber", "V-Shield Security", "Conference Spheres", "Food Court"],
    nearbyLandmarks: [
        { name: "Stock Exchange", distance: "0.2 KM" },
        { name: "Core Plaza", distance: "0.5 KM" }
    ],
    floorPlans: [
        { type: "Start-up Node", area: "800 sqft", price: 12000000, image: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800" },
        { type: "Enterprise Floor", area: "12000 sqft", price: 180000000, image: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800" }
    ]
  }
];
